[#g7,reftext=G.7]
=== (G.7) Stakeholders and requirements sources

ifdef::env-draft[]
TIP: _Groups of people who can affect the project or be affected by it, and other places to consider for information about the project and system. It lists stakeholders and other requirements sources. It should define stakeholders as categories of people, not individuals, even if such individuals are known at the time of writing. The main goal of chapter <<g7>> is to avoid forgetting any category of people whose input is relevant to the project. It also lists documents and other information that the project, aside from soliciting input from stakeholders, can consult for requirements information._  <<BM22>>
endif::[]
.Primary stakeholders (target side)
* Scholars of Buddhist textual history (religious studies, philology, palaeography)
* Supervisors and domain experts (project supervisor, capstone professor)
* Collections staff (archivists, curators, cataloguers)

.Secondary stakeholders
* Computer science researchers (AI, computer vision, OCR/HTR)
* Digital humanities researchers studying textual transmission/manuscript culture
* Teaching & outreach roles (instructors integrating the tool into coursework)

.End users
* Academic researchers assembling and studying fragments
* Graduate/undergraduate research assistants needing computational support
* Library/archives staff performing identification and metadata enhancement